async (page) => {
  page.setDefaultTimeout(10000);
  page.setDefaultNavigationTimeout(10000);
  const check = (value, message) => { if (!value) throw new Error(message); };
  const baseUrl = 'http://localhost:4000';
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(baseUrl);
  await page.getByRole('heading', { name: 'Соберите бургер' }).waitFor();
  await page.locator('a[href="/ingredients/bun"]').click();
  await page.getByRole('dialog', { name: 'Детали ингредиента' }).waitFor();
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'detached' });
  check(page.url() === baseUrl + '/', 'Ingredient modal did not restore the constructor route');
  await page.getByRole('button', { name: 'Добавить', exact: true }).nth(0).click();
  await page.getByRole('button', { name: 'Добавить', exact: true }).nth(1).click();
  await page.getByText('250', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Оформить заказ' }).click();
  await page.waitForURL('**/login');
  await page.locator('input[name="email"]').fill('student@example.test');
  await page.locator('input[name="password"]').fill('test-password');
  await page.getByRole('button', { name: 'Войти', exact: true }).click();
  await page.waitForURL(baseUrl + '/');
  await page.getByText('250', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Оформить заказ' }).click();
  await page.getByRole('dialog').getByText('4242', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  check(await page.getByText('Выберите булки', { exact: true }).count() === 2, 'Checkout did not clear the constructor');
  await page.getByText('Лента заказов', { exact: true }).click();
  const feedCard = page.locator('a[href="/feed/4242"]');
  await feedCard.waitFor();
  check((await feedCard.textContent()).includes('250'), 'Feed total is incorrect');
  await feedCard.click();
  await page.getByRole('dialog').getByText('2 x 100', { exact: true }).waitFor();
  check(await page.locator('header a[href="/feed"]').getAttribute('aria-current') === 'page', 'Feed menu is not active for its order');
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.goto(baseUrl + '/feed/4100');
  await page.getByText('#004100', { exact: true }).waitFor();
  check(await page.getByRole('dialog').count() === 0, 'Direct order route incorrectly opened a modal');
  await page.locator('header a[href="/profile"]').click();
  const name = page.locator('input[name="name"]');
  await name.waitFor();
  check(await name.inputValue() === 'Тестовый пользователь', 'Profile did not load user name');
  check(await page.getByRole('button', { name: 'Сохранить', exact: true }).count() === 0, 'Unchanged profile shows save button');
  await name.fill('Новое имя');
  await page.getByRole('button', { name: 'Отмена', exact: true }).click();
  check(await name.inputValue() === 'Тестовый пользователь', 'Profile cancel did not restore the name');
  await name.fill('Новое имя');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await page.locator('header').getByText('Новое имя', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Сохранить', exact: true }).waitFor({ state: 'detached' });
  await page.getByText('История заказов', { exact: true }).click();
  const privateCard = page.locator('a[href="/profile/orders/4242"]');
  await privateCard.waitFor();
  check((await privateCard.textContent()).includes('Выполнен'), 'History does not show order status');
  await privateCard.click();
  await page.getByRole('dialog').getByText('#004242', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await page.goto(baseUrl + '/profile/orders/4242');
  await page.getByText('#004242', { exact: true }).waitFor();
  check(await page.getByRole('dialog').count() === 0, 'Direct private order route incorrectly opened a modal');
  await page.goto(baseUrl + '/profile');
  await page.getByRole('button', { name: 'Выход', exact: true }).click();
  await page.waitForURL('**/login');
  await page.goto(baseUrl + '/profile/orders/4242');
  await page.waitForURL('**/login');
  await page.getByText('Восстановить пароль', { exact: true }).click();
  await page.locator('input[name="email"]').fill('student@example.test');
  await page.getByRole('button', { name: 'Восстановить', exact: true }).click();
  await page.waitForURL('**/reset-password');
  await page.locator('input[name="password"]').fill('new-test-password');
  await page.locator('input[name="token"]').fill('test-code');
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await page.waitForURL('**/login');
  await page.getByText('Зарегистрироваться', { exact: true }).click();
  await page.locator('input[name="name"]').fill('Новый пользователь');
  await page.locator('input[name="email"]').fill('new@example.test');
  await page.locator('input[name="password"]').fill('new-test-password');
  await page.getByRole('button', { name: 'Зарегистрироваться', exact: true }).click();
  await page.waitForURL(baseUrl + '/');
  await page.locator('header').getByText('Новый пользователь', { exact: true }).waitFor();
  await page.goto(baseUrl + '/ingredients/bun');
  await page.getByRole('heading', { name: 'Космическая булка' }).waitFor();
  check(await page.getByRole('dialog').count() === 0, 'Direct ingredient route incorrectly opened a modal');
  await page.goto(baseUrl + '/feed/missing');
  await page.getByText('Некорректный номер заказа', { exact: true }).waitFor();
  await page.goto(baseUrl + '/');
  check(errors.length === 0, 'Browser runtime errors: ' + errors.join('; '));
  return { passed: true, scenarios: ['ingredient modal/direct route', 'guest checkout/login return', 'authorized checkout and totals', 'feed modal/direct route', 'profile cancel/save', 'history modal/direct route', 'logout/private route protection', 'password recovery', 'registration', 'invalid order route'], runtimeErrors: errors.length };
}
